### ISSUE TITLE
复制功能

### ISSUE THREAD

**Issue by litianciucas** [helloworld-Co/html2md#10]
## Feature request（新功能建议）
您好，转换完之后，如果是需要保存到本地的话，我可以使用 保存为MD 这个功能。
但是如果我只是想复制下来，然后再粘贴进入我自己的笔记的话，就显得有点麻烦了，我要全选内容，再手动复制。
所以为了更加方便的复制，是否可以做个复制功能（点击按键，自动全选+复制内容）一键操作。

**Comment by litianciucas** [comment]
或者说，我点击一键转换后，转换后的内容直接进入剪切板，这样连复制按键都省了。

**Comment by hsl947** [comment]
@litianciucas 想法很好，安排！😁

**Comment by litianciucas** [comment]
回应真快，谢谢呀！祝你们越做越好。

**Comment by hsl947** [comment]
@litianciucas 已添加一键复制功能

**Comment by litianciucas** [comment]
效率真高！试了下，好用，多谢！

**Comment by hsl947** [comment]
@litianciucas 多谢支持
