### ISSUE TITLE
保留原网址

### ISSUE THREAD

**Issue by litianciucas** [helloworld-Co/html2md#11]
## Feature request（新功能建议）
您好，在url转MD时，我们往往是保存为自己的笔记，而原文的网址我觉得最好也能保留下来（1.方便追溯原文 2.原文往往还有一些其他人的评论可以参考），可以放在MD的最后，加上： 转自 ：www.xxxxx类似的。
或者是否可以在工具栏有个设置的选框，自己选择是否保留原文网站。
因为我每次使用，都会手动在MD最后加上原文网址，如果能自动添加是不是更加方便。谢谢！

**Comment by hsl947** [comment]
@litianciucas 这个功能原先是有的，后来由于某些原因暂时去掉了，可以考虑再加上；

**Comment by hsl947** [comment]
@litianciucas 已恢复保留原网址功能
