### ISSUE TITLE
url转md时，首行缩进转换错误。

### ISSUE THREAD

**Issue by litianciucas** [helloworld-Co/html2md#13]
## Bug report（问题描述）
转换csdn上面的文章时，首行缩进转换错误。

#### Steps to reproduce（问题复现步骤）

1. 原文中的首行缩进，转换后的MD中，整段全部缩进了，使得显示结果为一行显示全段。需要手动去掉前面的空行才能正常显示。
2. 原文链接：https://blog.csdn.net/zouxy09/article/details/7929348

#### Screenshot or Gif（截图或动态图）
1. csdn上原文如下：
![image](https://user-images.githubusercontent.com/32946194/131479843-9e6f4edd-96a8-467d-8c75-c0a8883d42b2.png)
2. https://www.helloworld.net/html2md 网站转换显示如下
![image](https://user-images.githubusercontent.com/32946194/131479977-b0d55b72-ec5f-4410-81c6-db5147cfc2d4.png)
3. 放入有道笔记中如下：
![image](https://user-images.githubusercontent.com/32946194/131480342-e6a8222f-9af2-4809-9d27-addba24ceb34.png)

#### Other relevant information（格外信息）
- Your OS: Windows 10 企业版
- Your broswer version: chrome 92.0.4515.159（正式版本） （64 位）

**Comment by hsl947** [comment]
@litianciucas markdown语法原生不支持缩进，只能自己添加缩进字符或空格字符；
缩进字符：`&emsp;` 或 `&ensp;`
空格字符：`&nbsp;`

**Comment by litianciucas** [comment]
那可以转换的时候，直接去掉首行缩进吗？我现在是，每段都自己删掉首行缩进，很麻烦。或者有个选项，是否去掉缩进。

**Comment by litianciucas** [comment]
因为现在是markdown直接把2个空格键，当成了一个markdown语法了（字体是蓝色的），这个语法使得原本的一段话，现在只用一行显示了，那既然markdown语法原生不支持缩进，那还不如直接去掉这2个空格。

**Comment by hsl947** [comment]
![image](https://user-images.githubusercontent.com/18359814/131507901-044b7c01-2ba9-4a69-9607-921fb52eade9.png)
经过排查，这些错误的缩进全部是 空格字符 `nbsp;` 
需要的话是可以把这些字符全部去掉，但是怕误删其他人为的空格字符（比如那些非首行的空格）。

**Comment by hsl947** [comment]
@litianciucas 这种空格属于非标准缩进，如果全局去掉，会误删不少空格

**Comment by litianciucas** [comment]
懂了，谢谢。那还是手动删掉吧。

**Comment by hsl947** [comment]
多谢理解和支持😆

**Comment by litianciucas** [comment]
我还有个疑问，可不可以判断，如果是首行的空格，就把他删掉呢？其他地方不管。

**Comment by hsl947** [comment]
@好的，这个我调研看看
