### ISSUE TITLE
无法获取动态渲染的网页的内容

### ISSUE THREAD

**Issue by gittig11** [helloworld-Co/html2md#14]
#### Steps to reproduce（问题复现步骤）

1. 输入掘金网址`https://juejin.cn/post/6844903617762492423`
2. 点击"一键转换"
3. 无法获取html内容。

#### Screenshot or Gif（截图或动态图）
略。

#### Other relevant information（格外信息）
- Your OS: Win10
- Your broswer version: Chrome 93.0.4577.82

#### 解决方法

除了使用 [puppeteer](https://www.npmjs.com/package/puppeteer)，有更好的解决方法吗? ==

**Comment by hsl947** [comment]
![image](https://user-images.githubusercontent.com/18359814/133880598-8d805cc9-f77b-41a1-94b2-84477a26d774.png)

@gittig11 你确定无法获取？？

**Comment by gittig11** [comment]
不要用官网的，你可以本地跑一下。 @hsl947

**Comment by gittig11** [comment]
```
// 掘金
    if (this.qUrl.includes('juejin.cn')) {
      const htmlContent = getBySelector('.markdown-body')
      const extraDom = htmlContent.querySelector('style')
      const extraDomArr = htmlContent.querySelectorAll('.copy-code-btn')
      extraDom && extraDom.remove()
      extraDomArr.length > 0 && extraDomArr.forEach((v) => { v.remove() })
      html2md.dom = htmlContent
      return this.returnFinalHtml()
    }
```
报错：
```
const extraDom = htmlContent.querySelector('style')
                                   ^
TypeError: Cannot read property 'querySelector' of null
```

**Comment by hsl947** [comment]
@gittig11 好的，我知道问题了

**Comment by gittig11** [comment]
@hsl947 好奇问一下是怎么解决的？==

**Comment by gittig11** [comment]
好吧，加个请求头...

**Comment by hsl947** [comment]
@gittig11 各种奇淫邪技，你懂的😉
