### ISSUE TITLE
segmentfault文章乱码

### ISSUE THREAD

**Issue by gittig11** [helloworld-Co/html2md#17]
#### Steps to reproduce（问题复现步骤）

1. 输入[segmentfault网址](https://segmentfault.com/a/1190000008484070)
2. 点击“一键转换”，内容为乱码。

#### Screenshot or Gif（截图或动态图）

![bug](https://raw.githubusercontent.com/gittig11/pic-cloud-repo/main/pic1/segmentfault文章乱码.png)

#### Other relevant information（格外信息）
- Your OS: win10
- Your broswer version: Chrome Version 94.0.4606.71 (Official Build) (64-bit)

**Comment by hsl947** [comment]
@gittig11 无法解决，这个很久之前就不行了，被sf屏蔽了

**Comment by gittig11** [comment]
@hsl947 sf屏蔽的原理是什么呢，怎么本地调试的时候是可以的？

**Comment by hsl947** [comment]
@gittig11 666，这都被你发现了，这个可以研究看看
