### ISSUE TITLE
访问微信公众号文章，getUrlHtml 接口返回程序异常了~

### ISSUE THREAD

**Issue by gittig11** [helloworld-Co/html2md#19]
对应的 pull request:

https://github.com/helloworld-Co/html2md/pull/18

**Comment by wu529778790** [comment]
这个不修复了么，好久了

**Comment by hsl947** [comment]
@wu529778790 不好意思，年底这几个月比较忙，忘了处理😅晚点我看看

**Comment by gittig11** [comment]
@hsl947 @wu529778790 开源项目是这样的吗，别人提的pull request就不鸟一下，借鉴完pull request的内容，直接修改代码并提交？不需要尊重一下提pull request的人的劳动成果？==!

**Comment by hsl947** [comment]
@gittig11 以前没操作过pr。已合并，但微调了些，感谢支持
