### ISSUE TITLE
大佬。。。本地跑不起来，，，

### ISSUE THREAD

**Issue by umlink** [helloworld-Co/html2md#20]
![image](https://user-images.githubusercontent.com/18066052/146373496-fa994b32-4d0e-4b75-ab5a-b525c1cc5a08.png)
[](url)

**Comment by umlink** [comment]
node: v14.17.6

![image](https://user-images.githubusercontent.com/18066052/146374453-cf47d1c5-f53c-4f3f-9ded-0f80f0cdae2e.png)

**Comment by hsl947** [comment]
@umlink 这个问题似曾相识，你安装的nuxt版本号多少

**Comment by umlink** [comment]
> 

v2.15.7

**Comment by umlink** [comment]
> @umlink 这个问题似曾相识，你安装的nuxt版本号多少

你的 nuxt node 版本多少我试试

**Comment by hsl947** [comment]
> > @umlink 这个问题似曾相识，你安装的nuxt版本号多少
> 
> 你的 nuxt node 版本多少我试试

nuxt  v2.14.12
node  v12.18.2

**Comment by umlink** [comment]
> 12.18.2

要不你本地删除 node_modules 重新跑跑试试 。。。

![image](https://user-images.githubusercontent.com/18066052/146497727-e2cbde33-206c-4bd7-8e68-44b6dc7f2938.png)

**Comment by hsl947** [comment]
@umlink emmm...我试了，是可以的
![微信截图_20211217153156](https://user-images.githubusercontent.com/18359814/146506860-6348d1ca-af43-40f7-b415-8607b8c76d8f.png)
![微信截图_20211217153220](https://user-images.githubusercontent.com/18359814/146506870-5b707d77-861e-464f-9065-df5f8493224e.png)

**Comment by umlink** [comment]
> 

大佬，您试试删除本机缓存，我怀疑是某些包取了全局的，删除缓存试试呢。。。我这确实是没跑起来

**Comment by umlink** [comment]
你本地preset-env 应该有缓存版本

参照 https://stackoverflow.com/questions/66325582/nuxt-js-cannot-find-module-babel-preset-env-lib-utils

**Comment by hsl947** [comment]
@umlink 这个缓存版本我倒是没注意呢，你是第一个反映这个问题的，我记住了😁

**Comment by GA23187** [comment]
> 

大佬 我这边也遇到这个问题了，我这边是运行之前是把package-lock文件删除了，重新npm i的，然后npm run dev会出现上面的错误，好像是@babel/preset-env的版本原因，我这边按这个文章（https://blog.csdn.net/qq_42849542/article/details/115958105）指定@babel/preset-env版本后就可以正常启动了
