### ISSUE TITLE
请问可以批量处理本地文件吗？

### ISSUE THREAD

**Issue by xdJumpING** [helloworld-Co/html2md#23]
## 请问可以批量处理本地文件吗？
因为需要保留链接，故爬取了几千条html数据，而不是TXT数据。请问这种情况需要如何处理？

#### Other relevant information（格外信息）
- Your OS: Win11
- Your broswer version: EDGE

**Comment by xdJumpING** [comment]
或者可以嵌入到JS写的爬虫插件里吗？

**Comment by hsl947** [comment]
@xdJumpING 可以的，项目是开源的，你可以复制关键源码到你的爬虫插件里，或直接调用我们[网站](https://www.helloworld.net/html2md)的 `getUrlHtml` 接口就能返回对应的html
