### ISSUE TITLE
请问可以打包成静态网站吗

### ISSUE THREAD

**Issue by hausen1012** [helloworld-Co/html2md#27]
我尝试着打包，但是 npm run build 后输出在哪呢？我想打包放在nginx

**Comment by hsl947** [comment]
> 我尝试着打包，但是 npm run build 后输出在哪呢？我想打包放在nginx

由于项目里用到了node端来抓取html，无法纯静态部署，输出目录是 .nuxt

**Comment by hausen1012** [comment]
感谢
