### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by getr00t** [helloworld-Co/html2md#28]
#### Steps to reproduce（问题复现步骤）
为什么运行失败啊，这是啥情况？node版本不对？你也没说限制版本吧

#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/12257416/199494036-4809a2e4-418f-43c9-baa2-a950f9735515.png)

#### Other relevant information（格外信息）
- Your OS:win10,64位
- Your broswer version:Chrome 已是最新版本
版本 107.0.5304.88（正式版本） （64 位）

**Comment by hsl947** [comment]
这边你试试node 12 吧
