### ISSUE TITLE
能否支持本地文件?

### ISSUE THREAD

**Issue by fatFire** [helloworld-Co/html2md#7]
## Feature request（新功能建议）
能否支持本地文件的转换?

**Comment by hsl947** [comment]
@fatFire 请描述清楚需求 😅

**Comment by fatFire** [comment]
> @fatFire 请描述清楚需求 😅

就是我有本地的html文件, 可否使用你们提供的转换网站进行转换成md格式呢

**Comment by hsl947** [comment]
@fatFire  这个功能其实已经有了😁，在另一个链接上。页面正在优化，很快就会放开，敬请期待，多谢支持！

**Comment by hsl947** [comment]
@fatFire 新功能已加入原有的html2md页面中，欢迎体验
